[phases.install]
cmds = [
  "npm install --include=dev --no-audit --no-fund"
]

[variables]
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_CACHE = "/root/.npm"

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:app"